name: Git version publish on version bump.

on:
  push:
    branches:
      - main
    paths:
      - 'version.cfg'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.0'

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh

    - name: Install dependencies
      run: npm ci

    - name: Increment version
      run: npm run publish.git
