name: Docs publish

permissions: write-all

on:
  push:
    branches:
      - main
    paths:
      - 'version.cfg'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # We need to use PAT alongside this
        # see: https://github.com/orgs/community/discussions/26220
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.0'

    - name: Configure Git
      run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"

    - name: Install dependencies
      run: npm ci

    - name: Publish the new version
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: npm run publish.docs
