name: Node.js Version Bump On Major Changes

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'src/**'
      - 'common/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.0'

    - name: Install dependencies
      run: npm ci

    - name: Increment version
      run: npm run inc.ver
